#!/bin/bash

set -euo pipefail
OLDIFS=$IFS
IFS=$'\n'

BLACKLIST=("@IgnoreRest" "@Ignore")
EXITCODE=0

COLOR_BEGIN="\033[1;31m"
COLOR_END="\033[0m"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    AGAINST=HEAD
else
    AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-only --cached $AGAINST` ; do
    for WORD in ${BLACKLIST[@]}; do
        if grep -q $WORD <(git show :"$FILE"); then
            echo -e "$FILE : $COLOR_BEGIN$WORD$COLOR_END"
            EXITCODE=1
        fi
    done
done

IFS=$OLDIFS

exit $EXITCODE
